### PR TITLE
Remove description for demo unit manager

### PR DESCRIPTION
**Pull request by tochi-y**

### CODE REVIEW

**Comment by dixonsiu** [comment]
@tochi-y 
Please add information in the commit log to explain why the sample UnitManager is not available anymore.

**Review by dixonsiu — COMMENTED** [review]
The user still need the UnitManager for their open-source project. I would suggest adding a few sentences explain the reason that the sample UnitManager is not available anymore. And what other method they can use.

**Comment by tochi-y** [comment]
> @tochi-y Please add information in the commit log to explain why the sample UnitManager is not available anymore.

I will add above comment to #179.

**Comment by tochi-y** [comment]
Closed due to #179 contains the content of this PR.

**Pull request closed without merging**
